server:
  port: ${PORT:8080}

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB
  cloud:
    gcp:
      credentials:
        location: file:C:\keys\google\api\gen-lang-client-0480462475-9ac936d659fa.json